# عدّل ملف netlify.toml:
echo '[build]
  publish = "build"
  command = "CI=false npm run build"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200' > netlify.toml

git add netlify.toml
git commit -m "Force CI=false in netlify.toml"
git push origin main